services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - fastapi-data:/app/data
      - fastapi-chroma:/app/chroma_db
    environment:
      - LOG_LEVEL=info
      - DATA_DIR=/app/data
    user: app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - fastapi-data:/app/data
    environment:
      - FASTAPI_URL=http://fastapi:8000
    # Add this user directive for the streamlit service too
    user: app
    depends_on:
      - fastapi
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

volumes:
  fastapi-data:
    # Add volume configuration for better control
    driver: local
  fastapi-chroma:
    # Add volume configuration for better control
    driver: local
