name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  uv-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv and Python 3.13.2
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13.2"
          version: "latest"
          enable-cache: true

      - name: Sync project dependencies
        run: uv sync

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests using uv
        run: uv run pytest
